repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff-check  # Lint code
        args: [--config=pyproject.toml, --fix]
      - id: ruff-format  # Format code
        args: [--config=pyproject.toml]