[project]
name = "pss-fleet-data-api"
version = "1.4.0"
license = {file = "LICENSE"}
description = "An API server for Pixelstarships Fleet Data"
authors = [
    { name = "The worst.", email = "theworstpss@gmail.com" }
]
dependencies = [
    "alembic>=1.13.2",
    "asyncpg>=0.29.0",
    "fastapi>=0.111.0",
    "fastapi-limiter>=0.1.6",
    "orjson>=3.10.6",
    "psycopg2-binary>=2.9.9",
    "python-dateutil>=2.9.0.post0",
    "sqlmodel>=0.0.19",
    "sqlalchemy-utils>=0.41.2",
]
readme = "README.md"
requires-python = ">= 3.12.3"

[tool.rye]
managed = true
virtual = true
dev-dependencies = [
    "autoflake>=2.3.1",
    "autopep8>=2.2.0",
    "black>=24.4.2",
    "flake8>=7.0.0",
    "flake8-black>=0.3.6",
    "flake8-bugbear>=24.4.26",
    "isort>=5.13.2",
    "pytest>=7.2.1",
    "pytest-asyncio>=0.23.7",
    "pytest-env>=1.1.3",
    "vulture>=2.11",
    "pytest-cov>=5.0.0",
    "coverage>=7.6.0",
]

[tool.autoflake]
in-place = true
remove-all-unused-imports = true
ignore-init-module-imports = true
recursive = true

[tool.black]
line-length = 150
target-version = ['py312']
include = '\.pyi?$'

[tool.isort]
src_paths = ["src"]
profile = "black"
line_length = 150
lines_after_imports = 2

[tool.vulture]
min_confidence = 100
paths = ["./src/api"]
sort_by_size = true
