"""Update pss_user table

Revision ID: 864bb00bc205
Revises: 8b04fbfef3f7
Create Date: 2024-07-30 12:28:08.609850+00:00

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "864bb00bc205"
down_revision: Union[str, None] = "8b04fbfef3f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("pss_user", "last_login_date", existing_type=postgresql.TIMESTAMP(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("pss_user", "last_login_date", existing_type=postgresql.TIMESTAMP(), nullable=False)
    # ### end Alembic commands ###
