"""Initialize database

Revision ID: 8b04fbfef3f7
Revises: 
Create Date: 2024-07-10 16:13:41.131567+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8b04fbfef3f7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("data_version", sa.Integer(), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("fleet_count", sa.Integer(), nullable=True),
        sa.Column("user_count", sa.Integer(), nullable=True),
        sa.Column("tournament_running", sa.Boolean(), nullable=False),
        sa.Column("max_tournament_battle_attempts", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("collection_id"),
    )
    op.create_index(op.f("ix_collection_collected_at"), "collection", ["collected_at"], unique=True)
    op.create_index(op.f("ix_collection_collection_id"), "collection", ["collection_id"], unique=False)
    op.create_table(
        "pss_alliance",
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("alliance_id", sa.Integer(), nullable=False),
        sa.Column("alliance_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("division_design_id", sa.Integer(), nullable=False),
        sa.Column("trophy", sa.Integer(), nullable=True),
        sa.Column("championship_score", sa.Integer(), nullable=True),
        sa.Column("number_of_members", sa.Integer(), nullable=True),
        sa.Column("number_of_approved_members", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.collection_id"],
        ),
        sa.PrimaryKeyConstraint("collection_id", "alliance_id"),
    )
    op.create_index(op.f("ix_pss_alliance_alliance_id"), "pss_alliance", ["alliance_id"], unique=False)
    op.create_index(op.f("ix_pss_alliance_collection_id"), "pss_alliance", ["collection_id"], unique=False)
    op.create_table(
        "pss_user",
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("alliance_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trophy", sa.Integer(), nullable=False),
        sa.Column("alliance_score", sa.Integer(), nullable=False),
        sa.Column("alliance_membership", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("alliance_join_date", sa.DateTime(), nullable=True),
        sa.Column("last_login_date", sa.DateTime(), nullable=False),
        sa.Column("last_heartbeat_date", sa.DateTime(), nullable=True),
        sa.Column("crew_donated", sa.Integer(), nullable=True),
        sa.Column("crew_received", sa.Integer(), nullable=True),
        sa.Column("pvp_attack_wins", sa.Integer(), nullable=True),
        sa.Column("pvp_attack_losses", sa.Integer(), nullable=True),
        sa.Column("pvp_attack_draws", sa.Integer(), nullable=True),
        sa.Column("pvp_defence_wins", sa.Integer(), nullable=True),
        sa.Column("pvp_defence_losses", sa.Integer(), nullable=True),
        sa.Column("pvp_defence_draws", sa.Integer(), nullable=True),
        sa.Column("championship_score", sa.Integer(), nullable=True),
        sa.Column("highest_trophy", sa.Integer(), nullable=True),
        sa.Column("tournament_bonus_score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.collection_id"],
        ),
        sa.PrimaryKeyConstraint("collection_id", "user_id"),
    )
    op.create_index(op.f("ix_pss_user_alliance_id"), "pss_user", ["alliance_id"], unique=False)
    op.create_index(op.f("ix_pss_user_collection_id"), "pss_user", ["collection_id"], unique=False)
    op.create_index(op.f("ix_pss_user_user_id"), "pss_user", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pss_user_user_id"), table_name="pss_user")
    op.drop_index(op.f("ix_pss_user_collection_id"), table_name="pss_user")
    op.drop_index(op.f("ix_pss_user_alliance_id"), table_name="pss_user")
    op.drop_table("pss_user")
    op.drop_index(op.f("ix_pss_alliance_collection_id"), table_name="pss_alliance")
    op.drop_index(op.f("ix_pss_alliance_alliance_id"), table_name="pss_alliance")
    op.drop_table("pss_alliance")
    op.drop_index(op.f("ix_collection_collection_id"), table_name="collection")
    op.drop_index(op.f("ix_collection_collected_at"), table_name="collection")
    op.drop_table("collection")
    # ### end Alembic commands ###
